name: yolo_env
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - ultralytics
  - gdal
  - libtiff
  - pip
  - pip:
      - gdown
